# Generated by Django 3.2.4 on 2022-03-14 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '__first__'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_limit_surfaces',
            field=models.BooleanField(default=False, verbose_name='Использовать "Зону покрытия"'),
        ),
        migrations.CreateModel(
            name='ClientSurfaceBind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Клиент')),
                ('surface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.surface', verbose_name='Поверхность (адрес)')),
            ],
            options={
                'verbose_name': 'Зона покрытия (адреса присутствия услуг)',
                'verbose_name_plural': 'Зоны покрытия (адреса присутствия услуг)',
            },
        ),
    ]
