__author__ = 'alexy'

INSTALLED_APPS = (
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'imagekit',
    'widget_tweaks',
    'annoying',
    'ckeditor',
    'rest_framework',
    'core',
    'api',
    'apps.ticket',
    'apps.administrator',
    'apps.moderator',
    'apps.landing',
    'apps.cabinet',
    'apps.city',
    'apps.client',
    'apps.adjuster',
    'apps.adjustertask',
    'apps.surface',
    'apps.journal',
    'apps.manager',
    'apps.incoming',
    'apps.sign',
    'apps.mobile',
    'django_cleanup',
)
